name: terraform-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      - name: Terraform validate (modules)
        run: |
          for d in modules/*; do
            (cd "$d" && terraform init -backend=false && terraform validate)
          done
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .
      - name: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
      - name: terraform-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: modules
          find-dir: modules
          output-method: inject
          recursive: true
          git-push: "true"